---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






# Remember basic molecule tests when updating






- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    overview.yml

  tags: overview



- name: Include downstream tasks within roles

  ansible.builtin.include_tasks: >-
    validate.yml

  tags: validate
