---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Information about the inventory host

  enasisnetwork.utility.overview:
    input:
      ansible:
        host: '{{ ansible_host | default }}'
        user: '{{ ansible_user | default }}'
        groups: '{{ group_names }}'
      orche_system: >-
        {{- orche_system
            if orche_system | default
            else omit -}}

  tags: always
