---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Update the inventory host applications

  ansible.builtin.dnf:
    name: '*'
    state: latest

  when:
    - inventory_hostname != 'localhost'
    - provision_family == ['almalinux', 'fedora']

  tags: always



- name: Update the inventory host applications

  ansible.windows.win_updates:
    reboot: true

  when:
    - inventory_hostname != 'localhost'
    - provision_family == 'windows'

  tags: always
