---
# Functions and routines associated with Enasis Network Orchestrations.

# This file is part of Enasis Network software eco-system. Distribution
# is permitted, for more information consult the project license file.






- name: Reboot inventory host operating system

  ansible.builtin.reboot:
    connect_timeout: 30
    pre_reboot_delay: 0
    post_reboot_delay: 15

  become: true

  when:
    - inventory_hostname != 'localhost'
    - provision_family == ['almalinux', 'fedora']

  tags: always



- name: Reboot inventory host operating system

  ansible.windows.win_reboot:

  become: false

  when:
    - inventory_hostname != 'localhost'
    - provision_family == 'windows'

  tags: always
